import os
import uuid
import json
import logging

from abc import ABC
from typing import Any, Union
from pathlib import Path
from .utils.config import config
from .utils.storage import Storage, BucketType
from .utils.artifact import ExportedArtifactTag, ArtifactType

class Task(ABC):
    """Represents a discrete unit of work within a data pipeline.

    The Task class manages the execution context, including configuration, 
    storage interfaces, and the lifecycle of input arguments and output artifacts.

    Attributes:
        config (Config): Global configuration settings for the execution environment.
        storage (Minio): The S3-compatible storage client for artifact persistence.
        name (str): The unique identifier or display name of the task.
        run_id (str): A unique UUID string representing the specific execution instance.
        arglist (List[str]): A list of args passing to execution function.
        args (Dict[str, Any]): Input parameters and data retrieved for the task.
        downloaded_artifacts (List[str]): Artifacts downloaded from upstream tasks.
        results (Dict[str, dict]): Key-value pairs of metadata to be passed to 
            downstream tasks.
        exports (List[dict]): A collection of results designated for final output.
        artifact_keys (List[str]): A list of keys to results of file-based outputs generated by 
            this task to be stored in cloud storage.
    """

    task_method_name: str
    def __init__(self, name: str, run_id: str, arglist: list[str]) -> None:
        self.config = config
        self.storage = Storage()
        self.name = name
        self.run_id = run_id
        self.arglist = arglist
        self.logger = logging.getLogger(self.name)

        self.args: dict[str, dict] = {}
        self.downloaded_artifacts: list[str] = []

        self.results: dict[str, dict] = {}
        self.artifact_keys: list[str] = []
        self.exports: list[dict] = []

    def add_result(self, key: str, name: str, value: Any, type: ArtifactType, attached: bool) -> None:
        self.logger.debug('Adding result of %s', key)
        self.results[key] = {
            'name': name,
            'value': value,
            'type': type.value,
            'attached': attached
        }

    def add_artifact(self, key: str, name: str, value: str, type: ArtifactType, attached: bool) -> None:
        """
        Registers a file-based output to be tracked and uploaded.
        
        Args:
            key: Internal reference key.
            name: Human-readable name.
            value: Local filesystem path to the file.
            exported: Whether this should also be flagged for final output.
        """
        self.add_result(key, name, value, type, attached)
        self.logger.debug('Adding artifact of %s', key)
        self.artifact_keys.append(key)

    def add_json_artifact(self, key: str, name: str, value: Union[dict, list], type: ArtifactType, attached: bool) -> None:
        """
        Dumps a dictionary to a local temporary JSON file and registers it as an artifact.
        """
        os.makedirs(self.config.cache_dir, exist_ok=True)
        filename = f"{key}_{uuid.uuid4().hex}.json"
        temp_path = os.path.join(self.config.cache_dir, filename)
        with open(temp_path, 'w', encoding='utf-8') as f:
            json.dump(value, f, indent=2, ensure_ascii=False)
        self.logger.debug(f"JSON artifact '{key}' dumped to {temp_path}")
        self.add_artifact(key, name, temp_path, type, attached)
    
    def add_export(self, result_key: str, tag: ExportedArtifactTag):
        self.logger.debug('Adding export of %s', result_key)
        self.exports.append({
            'result_key': result_key,
            'tag': tag.value
        })
        
    def load_artifacts(self, available_artifact_keys: list[str]):
        self.logger.debug("Available artifacts: %s", str(available_artifact_keys))
        for artifact_keys in available_artifact_keys:
            if not artifact_keys in self.arglist:
                continue
            filepath = os.path.join(self.config.cache_dir, uuid.uuid4().hex)
            self.logger.debug('Downloading artifact %s to %s', artifact_keys, filepath)
            self.storage.download(self.args[artifact_keys]['value'], filepath)
            self.downloaded_artifacts.append(filepath)
            self.args[artifact_keys]['value'] = filepath
            return filepath
    
    def cleanup_artifacts(self):
        for filepath in self.downloaded_artifacts:
            if os.path.exists(filepath):
                self.logger.debug('Removing downloaded artifact %s', filepath)
                os.remove(filepath)

    def store_artifacts(self):
        for artifact_key in self.artifact_keys:
            target = self.results[artifact_key]
            file_path = target['value']
            self.logger.debug('Uploading artifact %s', file_path)
            # calc name
            artifact_id = os.path.join(self.run_id, Path(file_path).name)
            # upload
            result = self.storage.upload_file(BucketType.STORAGE_BUCKET, artifact_id, file_path)
            # replace
            target['value'] = os.path.join(result.bucket_name, result.object_name)
            if os.path.exists(file_path):
                self.logger.debug('Removing uploaded artifact %s', file_path)
                os.remove(file_path)
    
    def load_cloud_args(self, artifact_file_ids: tuple[str, ...]):
        for artifact_id in artifact_file_ids:
            self.logger.debug('Loading cloud args from %s', artifact_id)
            data = self.storage.read_json(artifact_id)
            self.logger.debug('Loaded args of %s', str(list(data['results'].keys())))
            self.args.update(data['results'])
            self.load_artifacts(data['artifact_keys'])
    
    def store_cloud_args(self):
        self.store_artifacts()
        random_filepath = os.path.join(self.run_id, uuid.uuid4().hex)
            
        # store to storage
        passing_args = {
            'results': self.results,
            'artifact_keys': self.artifact_keys,
            'exports': self.exports
        }
        content = json.dumps(passing_args).encode('utf-8')
        result = self.storage.put_binary(
            BucketType.ARG_BUCKET, random_filepath, content, content_type="application/json"
        )
        return os.path.join(result.bucket_name, result.object_name)

    def on_run(self):
        args = [self.args.get(k, {}).get('value') for k in self.arglist]
        func = getattr(self, self.task_method_name)
        return func(*args)
    
    def run(self, *artifact_file_ids: str) -> str:
        try:
            # load passing args
            self.load_cloud_args(artifact_file_ids)
            # run job
            self.on_run()
            # store passing args
            return self.store_cloud_args()
        finally:
            # remove downloaded artifacts
            self.cleanup_artifacts()

    def local_run(self, *args):
        # store local args
        for arg_name, arg in zip(self.arglist, args):
            self.args[arg_name] = {
                'value': arg
            }
        # run job
        self.on_run()
        self.logger.info(json.dumps(self.results, indent=2))
